### PR TITLE
Added border rules for 600px 768px 992px and 1200px breakpoints

### PR DESCRIPTION
**Pull request by Pulkitxm**
solved https://github.com/manuel12/fluent-css/issues/10

### CODE REVIEW

**Review by manuel12 — CHANGES_REQUESTED** [review]
The border classes on this file don't seem to have the requested prefixes. Instead they have the original class names. Also the 768px media query doesn't seem to be added.

**Review by manuel12 — CHANGES_REQUESTED** [review]
Right now the media queries are not written well. They should be `@media screen and (min-width: [resolution])`.

Also at the moment the prefixes are not correct:

For the `min-width: 600px` media query border has no prefixes when it should have sm.  

On line 161 there is a repeated `min-width: 600px` media query. Media queries should not be repeated. 

And also the classes inside this query have `md` prefix when they should have `sm`.

The next media query `min-width: 768px` has prefix `lg` when it should be `md`.

The next media query `min-width: 992px` has prefix `xl` when it should be `lg`.

The next media query `min-width: 1200px` has prefix `xxl` when it should be `xl`.

**Review by Pulkitxm — COMMENTED** [review]
solved https://github.com/manuel12/fluent-css/pull/22

**Review by manuel12 — APPROVED** [review]
Well done, approved!

**Pull request merged**
